data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
data_dir: /home/yty/mfh/carla_data/town12_t_4/cooperative-vehicle-infrastructure
fusion:
  args:
    clip_pc: false
    proj_first: false
  core_method: IntermediateFusionMotion
loss:
  args:
    cls_weight: 1.0
    reg: 2.0
    traj: 0.5
  core_method: point_pillar_motion_loss
lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size:
  - 10
  - 20
model:
  args:
    anchor_number: 2
    backbone_fix: false
    base_bev_backbone:
      compression: 4
      layer_nums: &id001
      - 3
      - 4
      - 5
      layer_strides:
      - 2
      - 2
      - 2
      num_filters: &id002
      - 64
      - 128
      - 256
      num_upsample_filter:
      - 128
      - 128
      - 128
      resnet: true
      upsample_strides:
      - 1
      - 2
      - 4
      voxel_size: &id003
      - 0.44
      - 0.34
      - 6
    compression: 0
    detach_motion: true
    fusion_args:
      agg_operator:
        feature_dim: 256
        mode: MAX
      communication:
        gaussian_smooth:
          c_sigma: 1.0
          k_size: 5
        thre: 0.01
        visualize: false
      downsample_rate: 1
      dropout_rate: 0
      in_channels: 256
      layer_nums: *id001
      multi_scale: true
      n_head: 8
      num_filters: *id002
      only_attention: true
      voxel_size: *id003
    lidar_range: &id004
    - -88
    - -68
    - -2
    - 88
    - 68
    - 4
    max_cav: 2
    pillar_vfe:
      num_filters:
      - 64
      use_absolute_xyz: true
      use_norm: true
      with_distance: false
    point_pillar_scatter:
      num_features: 64
    shrink_header:
      dim:
      - 256
      input_dim: 384
      kernal_size:
      - 3
      padding:
      - 1
      stride:
      - 1
    voxel_size: *id003
  core_method: point_pillar_motion
name: carla_where2comm_motion
noise_setting:
  add_noise: false
  args:
    pos_mean: 0
    pos_std: 0.2
    rot_mean: 0
    rot_std: 0.2
optimizer:
  args:
    eps: 1e-10
    weight_decay: 1e-4
  core_method: Adam
  lr: 0.002
postprocess:
  anchor_args:
    cav_lidar_range: *id004
    feature_stride: 2
    h: 1.55
    l: 4.64
    num: 2
    r:
    - 0
    - 90
    w: 1.93
  core_method: VoxelPostprocessor
  gt_range: *id004
  max_num: 100
  nms_thresh: 0.15
  order: hwl
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.3
preprocess:
  args:
    max_points_per_voxel: 32
    max_voxel_test: 70000
    max_voxel_train: 32000
    voxel_size: *id003
  cav_lidar_range: *id004
  core_method: SpVoxelPreprocessor
root_dir: /home/yty/mfh/carla_data/town12_t_4/cooperative-vehicle-infrastructure/train.json
test_dir: /home/yty/mfh/carla_data/town12_t_4/cooperative-vehicle-infrastructure/test.json
train_params:
  batch_size: 1
  epoches: 31
  eval_freq: 10
  max_cav: 2
  save_freq: 10
traj_test: /home/yty/mfh/carla_data/town12_t_4/cooperative-vehicle-infrastructure/test_traj_coop.json
traj_train: /home/yty/mfh/carla_data/town12_t_4/cooperative-vehicle-infrastructure/train_traj_coop.json
validate_dir: /home/yty/mfh/carla_data/town12_t_4/cooperative-vehicle-infrastructure/test.json
yaml_parser: load_point_pillar_params
